# Generated by Django 3.1.5 on 2021-01-12 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_name', models.CharField(default=None, max_length=100)),
                ('chapter_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asvstool.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(default=None, max_length=256)),
                ('status', models.IntegerField(default=0)),
                ('nist', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('cwe', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('lvl1', models.BooleanField(default=True)),
                ('lvl2', models.BooleanField(default=True)),
                ('lvl3', models.BooleanField(default=True)),
                ('stand2', models.IntegerField(default=2)),
                ('stand3', models.IntegerField(default=2)),
                ('stand4', models.IntegerField(default=2)),
                ('stand5', models.IntegerField(default=2)),
                ('stand6', models.IntegerField(default=2)),
                ('stand7', models.IntegerField(default=4)),
                ('subsection_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asvstool.subsection')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=None, max_length=256)),
                ('date_made', models.DateTimeField(auto_now_add=True, verbose_name='data_utworzenia')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
