# Generated by Django 3.1.5 on 2021-01-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='status',
        ),
        migrations.CreateModel(
            name='ReqsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('result', models.BooleanField(blank=True, default=True)),
                ('project_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asvstool.project')),
                ('requirement_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asvstool.requirement')),
            ],
        ),
    ]
