# Generated by Django 3.1.5 on 2021-01-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0002_auto_20210112_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lvl1_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lvl2_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lvl3_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stand2_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stand3_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stand4_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stand5_project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='stand6_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stand7_project',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='reqsproject',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
