# Generated by Django 3.1.5 on 2021-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0003_auto_20210112_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqsproject',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='reqsproject',
            old_name='requirement_id',
            new_name='requirement',
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.ManyToManyField(through='asvstool.ReqsProject', to='asvstool.Requirement'),
        ),
        migrations.AlterUniqueTogether(
            name='reqsproject',
            unique_together={('project', 'requirement')},
        ),
    ]
