# Generated by Django 3.1.5 on 2021-01-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asvstool', '0004_auto_20210113_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqsproject',
            name='result',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='reqsproject',
            name='status',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
